mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.codepoet.website.pojo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
